services:
  server:
    image: caddy:2.11-alpine
    container_name: server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server/local.Caddyfile:/etc/caddy/Caddyfile
    networks:
      - heartbit

  my_app:
    image: my_app:latest
    container_name: my_app
    restart: on-failure
    build:
      context: ./src
      dockerfile: docker/Dockerfile
    env_file:
      - ./src/.env
    ports:
      - "20000:20000"
    depends_on:
      - server
    networks:
      - heartbit

networks:
  heartbit:
